version: "3"

services:
  database:
    image: mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3808:3808
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1