version: "3"

services:
  database:
    image: mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=blog
    ports:
      - 3808:3808
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password