version: "3"

services:
  app:
    image: blog:latest
    volumes:
      - ../static:/app/static
      - ../uploads:/app/uploads
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=blog
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - HIBERNATE_DLL_AUTO=create-drop
      - SMTP_HOST=smtp.strato.de
      - SMTP_PORT=587
      - SMTP_USERNAME=noreply@zeeshan-islam.de
      - SMTP_PASSWORD=pzWF8jsJ59UG7YD
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
  database:
    image: mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=blog
    volumes:
      - ../data/mariadb:/var/lib/mysql
    # ports:
    #   - 3808:3808
    #   - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # ports:
    #   - 9200:9200
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
